defaults: &defaults
  size:
    cart: 165
    
    thumb: 250
    detail: 1000
    fullsize: 800
    zoomin: 1000

local:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
